### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by riggsd** [riggsd/zcant#1]
Make sure the app builds on Windows 7, 10.

Provide a pre-compiled executable so end users don't need to know anything about Python or dependency installation.

**Comment by riggsd** [comment]
Wow, 1,250 lines of Python developed on Mac OS X, and it ran first try on Windows!

![zcant_screenshot_win7](https://cloud.githubusercontent.com/assets/647785/21708429/5333cb14-d38d-11e6-908f-1e971710b639.png)

Windows 7 Enterprise SP1, 64-bit
Python 2.7.12 :: Anaconda 2.5.0 (64-bit)
wxPython 3.0.0.0
numpy 1.11.1
matplotlib 1.5.1
(All dependencies must have been installed by the default Anaconda distribution; I didn't have to install a single package.)

**Comment by riggsd** [comment]
Drag-and-drop of a file failed, due to that hack CompositeDataObject code. Need to understand it better (it's handing back base SimpleDataObject objects rather than file- or text- specific subclasses) _or_ switch back to simply being a FileDropTarget for the time being.

```2017-01-05 18:36:21,493 DEBUG   OnData: 663, 343, 3
2017-01-05 18:36:21,513 DEBUG   <wx._misc.DataFormat; proxy of <Swig Object of type 'wxDat
aFormat *' at 0x66cde20> >, 15, ['AllFormats', 'Both', 'DataHere', 'DataSize', 'Format', '
FormatCount', 'Get', 'GetAllFormats', 'GetDataHere', 'GetDataSize', 'GetFormat', 'GetForma
tCount', 'GetPreferredFormat', 'IsSupported', 'PreferredFormat', 'Set', 'SetData', 'SetFor
mat', '__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__format__', '__getat
tribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__'
, '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy_
_', '__weakref__', 'this', 'thisown']
2017-01-05 18:36:21,513 DEBUG   OnDropFiles: 663, 343, ['\x14\x00\x00\x00\\\x00N\x00A\x00B
\x00\x00\x00\x00\x00\x01\x00\x00\x00G\x00:\x00\\\x00N\x00A\x00B\x00a\x00t\x00 \x00M\x00o\x
00n\x00i\x00t\x00o\x00r\x00i\x00n\x00g\x00\\\x00_\x00A\x00R\x00C\x00H\x00I\x00V\x00E\x00\\
\x00L\x00A\x00B\x00E\x00_\x00P\x00A\x00S\x00_\x00S\x00t\x00i\x00n\x00k\x00i\x00n\x00g\x00C
\x00a\x00v\x00e\x00_\x002\x000\x001\x006\x00-\x001\x002\x00-\x002\x000\x00_\x00-\x00_\x002
\x002\x00\\\x00D\x00a\x00t\x00a\x00\\\x00S\x00M\x003\x000\x004\x003\x004\x006\x00_\x00_\x0
00\x00_\x00_\x002\x000\x001\x006\x001\x002\x002\x000\x00_\x001\x008\x002\x007\x005\x003\x0
0.\x00w\x00a\x00v\x00\x00\x00\x00\x00']
2017-01-05 18:36:21,513 DEBUG

load_file:  ¶   \ N A B     ☺   G : \ N A B a t   M o n i t o r i n g \ _ A R C H I V E \
L A B E _ P A S _ S t i n k i n g C a v e _ 2 0 1 6 - 1 2 - 2 0 _ - _ 2 2 \ D a t a    S M
 3 0 4 3 4 6 _ _ 0 _ _ 2 0 1 6 1 2 2 0 _ 1 8 2 7 5 3 . w a v
2017-01-05 18:36:21,532 ERROR   Barfed loading file: ¶   \ N A B     ☺   G : \ N A B a t
 M o n i t o r i n g \ _ A R C H I V E \ L A B E _ P A S _ S t i n k i n g C a v e _ 2 0 1
 6 - 1 2 - 2 0 _ - _ 2 2 \ D a t a \ S M 3 0 4 3 4 6 _ _ 0 _ _ 2 0 1 6 1 2 2 0 _ 1 8 2 7 5
 3 . w a v
Traceback (most recent call last):
  File "C:\Users\dariggs\workspace\zcant\zcant\gui.py", line 618, in load_file
    times, freqs, amplitudes, metadata = self.extract(path)
  File "C:\Users\dariggs\workspace\zcant\zcant\gui.py", line 596, in extract
    raise Exception('Unknown file type: %s', path)
Exception: ('Unknown file type: %s', '\x14\x00\x00\x00\\\x00N\x00A\x00B\x00\x00\x00\x00\x0
0\x01\x00\x00\x00G\x00:\x00\\\x00N\x00A\x00B\x00a\x00t\x00 \x00M\x00o\x00n\x00i\x00t\x00o\
x00r\x00i\x00n\x00g\x00\\\x00_\x00A\x00R\x00C\x00H\x00I\x00V\x00E\x00\\\x00L\x00A\x00B\x00
E\x00_\x00P\x00A\x00S\x00_\x00S\x00t\x00i\x00n\x00k\x00i\x00n\x00g\x00C\x00a\x00v\x00e\x00
_\x002\x000\x001\x006\x00-\x001\x002\x00-\x002\x000\x00_\x00-\x00_\x002\x002\x00\\\x00D\x0
0a\x00t\x00a\x00\\\x00S\x00M\x003\x000\x004\x003\x004\x006\x00_\x00_\x000\x00_\x00_\x002\x
000\x001\x006\x001\x002\x002\x000\x00_\x001\x008\x002\x007\x005\x003\x00.\x00w\x00a\x00v\x
00\x00\x00\x00\x00')```

**Comment by riggsd** [comment]
Also need to fix the nav button scaling.

See: https://groups.google.com/forum/#!topic/wx-users/GE8snC1zwPc

(But note that `GetContentScaleFactor()` appears to not be in wxPython 3.0 classic)
